export const config = {
    SIM_RESOLUTION: 512, //simres
    DYE_RESOLUTION: 2160, //output res 
    PALETTE_RESOLUTION: 128,
    ASPECT: 1.0,
    FLOW: 3.44,
    SPLAT_FLOW: 0.15,
    VELOCITYSCALE: 1.0,
    CAPTURE_RESOLUTION: 1024, //screen capture res 
    DENSITY_DISSIPATION: .25, //def need to figure out this one, think perhaps bc im squaring the color in splatColor
    VELOCITY_DISSIPATION: 0.2,
    PRESSURE: 0.8,
    PRESSURE_ITERATIONS: 50,
    CURL: 30,
    SPLAT_RADIUS: 0.15,
    SPLAT_FORCE: 6000,
    PAUSED: false,
    BACK_COLOR: { r: 0, g: 0, b: 0 },
    TRANSPARENT: false,
    FORCE_MAP_ENABLE: true,
    DENSITY_MAP_ENABLE: true, 
    COLOR_MAP_ENABLE:true,
    EXPONENT: 1.0,
    PERIOD: 3.0,
    RIDGE: 1.0,
    AMP: 1.0,
    LACUNARITY: 2.0,
    GAIN: 0.5,
    OCTAVES: 4,
    MONO: false,
    NOISE_TRANSLATE_SPEED: 0.15,
    DISPLAY_FLUID: true,
    RESET: false,
    RANDOM: false,
    WIND_SCALE: .05,
    WIND_TYPE: 8,
    BDRF_DIFFUSE: .196,
    BDRF_NORMALS: .081352,
    BDRF_FRESNAL: .105,
    BDRF_ROUGH: .57256,
    BDRF_SPECULAR: .345,
    LUT: 1.0
};
